services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: 102022400212_Penawaran-Service_App
    ports:
      - "8000:8000"
    volumes:
      - .:/var/www/html
    environment:
      - DB_CONNECTION=sqlite
      - DB_DATABASE=/var/www/html/database/database.sqlite